
// example
export const EXAMPLE__TEXT_APPEND  = 'EXAMPLE__TEXT_APPEND';
export const EXAMPLE__TEXT_PREPEND = 'EXAMPLE__TEXT_PREPEND';
export const EXAMPLE__MERGE        = 'EXAMPLE__MERGE';
export const EXAMPLE__RESET        = 'EXAMPLE__RESET';

// exampleItems
export const EXAMPLE_ITEMS__SET_ROWS       = 'EXAMPLE_ITEMS__SET_ROWS';
export const EXAMPLE_ITEMS__SET_ROWS_ORDER = 'EXAMPLE_ITEMS__SET_ROWS_ORDER';
export const EXAMPLE_ITEMS__DELETE_ROW     = 'EXAMPLE_ITEMS__DELETE_ROW';
